# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*
- release/*

pool:
  name: 'Self-Hosted'

variables:
  imageName: 'demo-application'

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Determine Version

- task: Docker@2
  inputs:
    containerRegistry: 'Local docker registry'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'DemoApplication/Dockerfile'
    tags: '$(GitVersion.SemVer)'

- task: HelmDeploy@0
  displayName: Helm package
  inputs:
    command: 'package'
    chartPath: 'deployment/helm/demo-application'
    chartVersion: '$(GitVersion.SemVer)'
    destination: '$(Build.ArtifactStagingDirectory)/helm/charts'
    arguments: '--app-version $(GitVersion.SemVer)'

- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'Local octopus server'
    Space: 'Spaces-1'
    Package: '$(Build.ArtifactStagingDirectory)/helm/charts/*.tgz'
    Replace: 'IgnoreIfExists'

- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'Local octopus server'
    Space: 'Spaces-1'
    ProjectGroup: 'ProjectGroups-1'
    ProjectName: 'Projects-1'
    ReleaseNumber: '$(GitVersion.SemVer)'
    Channel: 'Channels-1'
    DeployToEnvironment: 'Environments-1'