# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'Self-Hosted'

variables:
  imageName: 'demo-application'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Local docker registry'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'DemoApplication/Dockerfile'

- task: HelmDeploy@0
  displayName: Helm package
  inputs:
    command: 'package'
    chartPath: 'deployment/helm/demo-application'
    destination: '/helm/charts'

- task: CmdLine@2
  inputs:
    script: 'curl -X POST http://localhost:8080/api/packages/raw -H "X-Octopus-ApiKey: $(octopus-api-key)" -F "data=@demo-application-0.1.0.tgz"'
    workingDirectory: '/helm/charts'