# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*
- release/*

pool:
  name: 'Self-Hosted'

variables:
  imageName: 'demo-application'

stages:
- stage: Setup
  jobs:
    - job: Git
      steps:
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      - task: gitversion/execute@0
        displayName: Determine Version
        name: GitVersion
        
      - bash: echo "##vso[task.setvariable variable=test;isOutput=true]Hello"
        name: output

    - job: Env
      steps:
      - task: Bash@3
        displayName: Print environment
        inputs:
          targetType: 'inline'
          script: env | sort

- stage: Build
  jobs:
  - job: Application
    variables:
      test: $[ stageDependencies.Setup.Git.outputs['output.test'] ]
      fullSemVer: $[ stageDependencies.Setup.Git.outputs['GitVersion'] ]
      dockertag: $[ stageDependencies.Setup.Git.outputs['GitVersion.FullSemVer'] ]
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Local docker registry'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'DemoApplication/Dockerfile'
        tags: '$(dockertag)'

  - job: Helm
    dependsOn: Application
    steps:
    - task: HelmDeploy@0
      displayName: Helm package
      inputs:
        command: 'package'
        chartPath: 'deployment/helm/demo-application'
        chartVersion: '$(fullSemVer)'
        destination: '$(Build.ArtifactStagingDirectory)/helm/charts'
        arguments: '--app-version $(dockertag)'

- stage: PushChartAndCreateRelease
  jobs:
  - job: Push
    steps:
      - task: OctopusPush@4
        displayName: Ocotopus push
        inputs:
          OctoConnectedServiceName: 'Local octopus server'
          Space: 'Spaces-1'
          Package: '$(Build.ArtifactStagingDirectory)/helm/charts/*.tgz'
          Replace: 'true'

  - job: Release
    dependsOn: Push
    steps:
    - task: OctopusCreateRelease@4
      displayName: Master release
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        OctoConnectedServiceName: 'Local octopus server'
        Space: 'Spaces-1'
        ProjectGroup: 'ProjectGroups-1'
        ProjectName: 'Projects-1'
        ReleaseNumber: '$(fullSemVer)'
        Channel: 'Channels-1'
        
    - task: OctopusCreateRelease@4
      displayName: Feature release
      condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        OctoConnectedServiceName: 'Local octopus server'
        Space: 'Spaces-1'
        ProjectGroup: 'ProjectGroups-1'
        ProjectName: 'Projects-1'
        ReleaseNumber: '$(fullSemVer)'
        Channel: 'Channels-21'