version: "3.9"
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./dockerregistry/data:/var/lib/registry
      - ./dockerregistry/certs:/certs
      - ./dockerregistry/auth:/auth
    networks: 
      default:
        aliases:
          - registry.docker.local

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Passw0rd!
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Passw0rd!", "-Q", "select 1"]
      interval: 10s
      retries: 10
    volumes:
      - sqlvolume:/var/opt/mssql
  octopus-server:
    build: ./octopus
    privileged: false
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      OCTOPUS_SERVER_NODE_NAME: octopus_test
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: Passw0rd!
      MASTER_KEY: fnzv1XVQcLldR4BJzAvvTw==
      DB_CONNECTION_STRING: Server=db,1433;Database=OctopusDeploy;User=sa;Password=Passw0rd!
      DISABLE_DIND: 'N'
    ports:
      - 8080:8080
      - 11111:10943
    depends_on:
      - db
    volumes:
      - repository:/repository
      - artifacts:/artifacts
      - taskLogs:/taskLogs
      - cache:/cache
      - import:/import

networks:
  default:

volumes:
  repository:
  artifacts:
  taskLogs:
  cache:
  import:
  sqlvolume: