---
kind: Namespace
apiVersion: v1
metadata:
  name: demo-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-deployer
  namespace: demo-development
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: demo-development
  name: demo-deployer-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]     
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-deployer-binding
  namespace: demo-development
subjects:
- kind: ServiceAccount
  name: demo-deployer
  apiGroup: ""
roleRef:
  kind: Role
  name: demo-deployer-role
  apiGroup: ""