services:
  agent:
  image: dockeragent:latest
  environment:
    AZP_URL: https://dev-ops.azure.local/DefaultCollection
    AZP_TOKEN: iilxozaek4ycx6j4ixnyei7sz2jej6gzcxvqzscluz4obyzl3ktq
    AZP_AGENT_NAME: dockeragent
    AZP_POOL: Self-Hosted
    AZP_AGENT_DOWNGRADE_DISABLED: "true"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  default: